### ISSUE TITLE
MSVC Compiler Flags Does Not Work

### ISSUE THREAD

**Issue by threeal** [threeal/cmake-action#27]
Failed to specify compiler flags in MSVC style (usually started with forward slash `/`)

E.g. this one does not work on `windows-latest`:
```yaml
- name: Configure and build this project
  uses: threeal/cmake-action@v1.0.0
  with:
    cxx-compiler: cl
    cxx-flags: /WX
```
See [this run](https://github.com/threeal/result/actions/runs/3918786112/jobs/6699377322).
